---
title: "Output"
output: 
  html_notebook
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
#saveRDS(df, 'C:/Users/ru21406/YandexDisk/PhD Research/health-ses-policies/data/df.rds')
library(ggplot2)
library(readxl)
library(plyr); library(dplyr)
library(magrittr)
library(lavaan)
library(lme4)
library(ggformula)
library(kableExtra)
library(ggExtra)
```

```{r echo=FALSE}
policy_names_3 = c('environment_planning_cultural',
                   'pub_health_soc_care',
                   'housing_transport',
                   'education'
                   )

df = readRDS('C:/Users/ru21406/YandexDisk/PhD Research/health-ses-policies/data/df.rds')

# Flipping the sign
df$stroke_rate = -df$stroke_rate
df$z_mh_rate = -df$z_mh_rate
df$antidep_rate = -df$antidep_rate
df$est_qof_dep = -df$est_qof_dep
df$prop_ibesa = -df$prop_ibesa
df$samhi_index = -df$samhi_index

# lags
lags =  collapse::L(df, n = 1:3, by = ~ lsoa11,
          t = ~ time, cols = which(colnames(df) %in% c(policy_names_3,
                                                       'prop_ibesa',
                                                       'est_qof_dep', 
                                                       'antidep_rate',
                                                       'z_mh_rate',
                                                      'samhi_index')))
#Ldf = df %>% left_join(lags) 

# LSOA deprivation groups
#Ldf = df %>% left_join(lags, by = c("lsoa11", "time")) 
#Ldf = Ldf[!is.na(df$Income_Score), ]

df_lad = df %>% group_by(LAD21CD, year) %>%
  dplyr::summarise(samhi_index = mean(samhi_index),
            .groups = 'drop',
            social = mean(social, na.rm = T),
            education = mean(education, na.rm = T),
            lsoa_ses_score = mean(lsoa_ses_score, na.rm = T)) %>%
  ungroup() 
df_lad = as.data.frame(df_lad)
df_lad$wealthy = ifelse(df_lad$IMD_rank > mean(df_lad$IMD_rank), 1, 0)

 
```



```{r echo=FALSE, fig.height=4, fig.width=7}
p1 = df_lad %>% na.omit() %>%
  ggplot(aes(x = social, 
             y = education, 
             group = LAD21CD))+
  labs(y = 'Mental Health Index',
       x = 'Public Health and Social Care Spending, £1000 per person') +
  geom_smooth(method="lm", se = F,
              colour = 'grey78',
              formula = 'y ~ x',
              size = 0.7
  ) +
  geom_point(aes(color = lsoa_ses_score),
    size = 1.5, alpha = 0.4,
    #color = 'darkgrey'
  )+
  scale_colour_gradient(high = "steelblue2",
                        low = 'darkred') + 
  theme_light() +
  theme(legend.position = c(.8, 0.2),
        legend.direction = 'horizontal',
        legend.key.size = unit(.7, 'cm'),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 14),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14)) 

p2 = df_lad %>% na.omit() %>%
  ggplot(aes(x = housing_transport, 
             y = samhi_index, 
             group = LAD21CD))+
  labs(y = 'Mental Health Index',
       x = 'Housing and Transport Spending, £1000 per person') +
  geom_smooth(method="lm", se = F,
              colour = 'grey78',
              formula = 'y ~ x',
              size = 0.7
  ) +
  geom_point(aes(color = IMD_decile),
             size = 1.5, alpha = 0.4,
             #color = 'darkgrey'
  )+
  scale_colour_gradient(high = "steelblue2",
                        low = 'darkred') + 
  theme_light() +
  theme(legend.position = c(.8, 0.2),
        legend.direction = 'horizontal',
        legend.key.size = unit(.7, 'cm'),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 14),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14))  

 p3 = df_lad %>% na.omit() %>%
  ggplot(aes(x = environment_planning_cultural, 
             y = samhi_index, 
             group = LAD21CD))+
  labs(y = 'Mental Health Index',
       x = 'Environmental, Planning, Cultural Spending, £1000 per person') +
  geom_smooth(method="lm", se = F,
              colour = 'grey78',
              formula = 'y ~ x',
              size = 0.7
  ) +
  geom_point(aes(color = IMD_decile),
             size = 1.5, alpha = 0.4
  )+
  scale_colour_gradient(high = "steelblue2",
                        low = 'darkred') + 
  theme_light() +
  theme(legend.position = c(.8, 0.2),
        legend.direction = 'horizontal',
        legend.key.size = unit(.7, 'cm'),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 14),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14)) 
 
  p4 = df_lad %>% na.omit() %>%
  ggplot(aes(x = education, 
             y = samhi_index, 
             group = LAD21CD))+
  labs(y = 'Mental Health Index',
       x = 'Education Spending, £1000 per person') +
  geom_smooth(method="lm", se = F,
              colour = 'grey78',
              formula = 'y ~ x',
              size = 0.7
  ) +
  geom_point(aes(color = IMD_decile),
             size = 1.5, alpha = 0.4
  )+
  scale_colour_gradient(high = "steelblue2",
                        low = 'darkred') + 
  theme_light() +
  theme(legend.position = c(.8, 0.2),
        legend.direction = 'horizontal',
        legend.key.size = unit(.7, 'cm'),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 14),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14)) 
```


```{r fig.height=4, fig.width=7}
setwd("C:/Users/ru21406/YandexDisk/PhD Research/Data")
ggMarginal(p1, type="histogram", fill = "lightgrey")
ggsave("p1.jpeg")
ggMarginal(p2, type="histogram", fill = "lightgrey")
ggsave("p2.jpeg")
ggMarginal(p3, type="histogram", fill = "lightgrey")
ggsave("p3.jpeg")
ggMarginal(p4, type="histogram", fill = "lightgrey")
ggsave("p4.jpeg")
```


```{r echo=FALSE}
df %<>% group_by(LAD21CD) %>% dplyr::mutate(n = n())
m = list()
for (i in 1:3){
  lags1 = lags %>% dplyr::select(starts_with(paste0('L', i)), lsoa11, time)
  L1df = df[,c('samhi_index',
            'lsoa11',
            'time',
            'Income_decile',
            'n')] %>% 
    left_join(lags1, by = c("lsoa11", "time"))%>% 
  rename_at(vars(starts_with(paste0('L', i))), funs(substr(.,4,nchar(.))))
  m1 = lmer(samhi_index ~ 
              pub_health_soc_care + 
              environment_planning_cultural + 
              housing_transport + 
              Income_decile + 
              time +
              scale(n) +
            (1 | lsoa11), data = L1df)
m[[i]] = m1
}

full = lmer(samhi_index ~ 
              pub_health_soc_care + 
              environment_planning_cultural + 
              housing_transport + 
              Income_decile + 
              time +
              scale(n) +
            (1 | lsoa11), data = df)

sum1 = modelsummary::msummary(list(
  "Full" = full,
  "Lag 1" = m[[1]], 
  "Lag 2" = m[[2]], 
  "Lag 3" = m[[3]]), stars = F, statistic = NULL, output = 'data.frame'
  ) 
split = list(as.numeric(sum1[2,4:7]), as.numeric(sum1[3,4:7]), as.numeric(sum1[4,4:7]))

sum = modelsummary::msummary(list(
  "Full" = full,
  "Lag 1" = m[[1]], 
  "Lag 2" = m[[2]], 
  "Lag 3" = m[[3]]), stars = T, statistic = NULL, output = 'data.frame'
  ) 

```

```{r echo=FALSE}

#| tbl-colwidths: [85,5,5,5]

sum[,c(2,4,5,6,7)] %>%
  kbl() %>%
  row_spec(2:4, bold = T, color = "white", background = "#D7261E") %>%
  kable_minimal()%>%
  kable_classic(html_font = "Cambria")
```



```{r}
seq_models_coefs = ShortLongRunExtract(models = c('only_growth_fit',
                                                  'growth_impulses_fit',
                                                  'growth_impulses_pastst_fit'))


mental_indices_coefs = ShortLongRunExtract(models = 
                                             c('growth_impulses_pastst_fit',
                                               'mental_sub1_fit',
                                               'mental_sub2_fit',
                                               'mental_sub3_fit',
                                               'mental_sub4_fit'))
```



```{r}
seq_models_coefs_ = seq_models_coefs[c(9:12,19:27),]
seq_models_numb = seq_models_coefs_[, c(2,6)]
list_seq_models = split(seq_models_numb, 1:nrow(seq_models_numb))
list_seq_models = lapply(list_seq_models, as.numeric)
seq_models_coefs_$'' = ''
rownames(seq_models_coefs_) = NULL
```


```{r echo=FALSE}
seq_models_coefs_ = seq_models_coefs[c(9:12,19:27#,38:40, 42:44
                                       ), c(1,2,4,6)]
rownames(seq_models_coefs_) = NULL

seq_models_coefs_[,-1] = sapply(seq_models_coefs_[,-1], as.numeric)
seq_models_coefs_[,-1] = round(seq_models_coefs_[,-1], 2)

seq_models_coefs_$Policies = c(
                             'Intercept Mental ~~ Slope Mental',
                             'Intercept SocialCare ~~ Slope SocialCare',
                             'Intercept Housing ~~ Slope Housing',
                             'Intercept Environment ~~ Slope Environment',
                             'Slope Mental ~~ Slope SocialCare',
                             'Slope Mental ~~ Slope Housing',
                             'Slope Mental ~~ Slope Environment',
                             'Slope SocialCare ~~ Slope Housing',
                             'Slope SocialCare ~~ Slope Environment',
                             'Slope Housing ~~ Slope Environment',
                             'Intercept Mental ~~ Slope SocialCare',
                             'Intercept Mental ~~ Slope Housing',
                             'Intercept Mental ~~ Slope Environment'#,
                             #'Social Care', 
                             #'Housing & Transport',
                             #'Environment & Culture',
                             #'Social Care', 
                             #'Housing & Transport',
                             #'Environment & Culture'
                             )
seq_models_coefs_[,1] = NULL
seq_models_coefs_ %<>% dplyr::select(Policies, everything())
colnames(seq_models_coefs_) = c('',  
                     #"Growth Only", 
                     #"Growth+Short",
                     #'Growth+Short+Long',
                     'I',
                     'II',
                     'III')

seq_models_coefs_ %>%
  kbl(caption = "Step-by-Step Models") %>%
  kable_minimal() %>%
  kable_paper(full_width = F)%>% 
  column_spec(4, color = "black", bold = T,# width = '.5cm',
              background = ifelse(abs(seq_models_coefs_[,4]) > 0.2, 'maroon', 'none'))#%>%
  #row_spec(0, angle = -45)
  #add_header_above(c(" " = 1,
  #                   "Growth Only" = 2, 
  #                   "Growth + Impulses" = 2,
  #                   'Growth + Impulses + Past States' = 2,
  #                   'Spline' = 1))%>%
  #pack_rows("Growth Parameters", 1, 36)  %>%
  #pack_rows("Short-Run", 37, 40) %>%
  #pack_rows("Long-Run", 41, 44)  %>%
  #column_spec(1, width = '10cm')#%>% 
  #scroll_box(width = "900px", height = "500px") %>% 
  #column_spec(8, image = spec_plot(list_seq_models, same_lim = FALSE,col="lightblue",type="l"))
```


```{r Growth Curve, fig.height=10, fig.width=7}
temp = seq_models_coefs[c(1:55), c(1,6)]
names(temp) = c('cor_name', 'pars')
temp %<>% tidyr::separate(cor_name, c('X', 'Y'), ' \\|\\| ')# %>% dplyr::filter(!X==Y)
pivot_initial = as.data.frame(with(temp,
     tapply(pars, list(X, Y), FUN = identity)))

pivot = apply(pivot_initial, 2, function(x) ifelse(is.na(x), '', x))
pivot = cov2cor(getCov(as.matrix(pivot, lower=F)))

pivot = as.data.frame(round(pivot, digits = 2))
fun = function(x) {
  x = ifelse(x<0, paste0('-', substr(as.character(x), 3, 5)), 
                         ifelse(x>0 & !x==1, substr(as.character(x), 2, 4), 
                                ifelse(x==1, '1.00', '.00')))
  x = ifelse(x == 0.0, paste0(x, '0'), x)
  return(x)
  }
pivot = as.data.frame(as.matrix(sapply(pivot, fun)))
pivot[lower.tri(pivot, diag = F)] <- ''

# col and row names
all_nam = c('Intercept Mental',
             'Intercept SocialCare',
             'Intercept Housing',
             'Intercept Environment',
             'Intercept Education',
             'Slope Mental',
             'Slope SocialCare',
             'Slope Housing',
             'Slope Environment',
             'Slope Education'
                   )
pivot = as.data.frame(pivot)
pivot$Policies = all_nam
rownames(pivot) = NULL
pivot %<>% dplyr::select(Policies, everything())
colnames(pivot) = c('', all_nam)

#pivot[1,2] = cell_spec(pivot[1,2], background = "white")

pivot %>%
  kbl(#caption = "Step-by-Step Models",
    booktabs = F, escape = F, centering = T) %>%
 # kable_classic_2() %>%
  #kable_paper("striped", full_width = F) %>% 
  column_spec(9, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,9])) > 0.4 &
                                    !pivot[,9] == '' & !pivot[,9] == pivot[8,9],
                                  'lightblue', 'white')) %>% 
  column_spec(2, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,2])) > 0.4 &
                                    !pivot[,2] == '' & !pivot[,2] == pivot[1,2],
                                  'lightblue', 'white'))%>% 
  column_spec(3, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,3])) > 0.4 &
                                    !pivot[,3] == '' & !pivot[,3] == pivot[2,3],
                                  'lightblue', 'white'))%>% 
  column_spec(4, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,4])) > 0.4 &
                                    !pivot[,4] == '' & !pivot[,4] == pivot[3,4],
                                  'lightblue', 'white'))%>% 
  column_spec(5, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,5])) > 0.4 &
                                    !pivot[,5] == '' & !pivot[,5] == pivot[4,5],
                                  'lightblue', 'white'))%>% 
  column_spec(6, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,6])) > 0.4 &
                                    !pivot[,6] == '' & !pivot[,6] == pivot[5,6],
                                  'lightblue', 'white'))%>% 
  column_spec(7, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,7])) > 0.4 &
                                    !pivot[,7] == '' & !pivot[,7] == pivot[6,7],
                                  'lightblue', 'white'))%>% 
  column_spec(8, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,8])) > 0.4 &
                                    !pivot[,8] == '' & !pivot[,8] == pivot[7,8],
                                  'lightblue', 'white'))%>% 
  column_spec(10, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,10])) > 0.4 &
                                    !pivot[,10] == '' & !pivot[,10] == pivot[9,10],
                                  'lightblue', 'white'))%>% 
  column_spec(11, color = "black", #bold = T,
              background = ifelse(abs(as.numeric(pivot[,11])) > 0.4 &
                                    !pivot[,11] == '' & !pivot[,11] == pivot[10,11],
                                  'lightblue', 'white')) %>%
  row_spec(0, align='justify') %>%
  column_spec(1, width = '4cm')
  
```


#
#
#
#



\newpage




```{r echo=FALSE, fig.height=10, fig.width=7}

mental_indices_coefs_initial = mental_indices_coefs[c(57:60, 62:65), c(1,3,5,9,11)]
mental_indices_coefs_ = mental_indices_coefs[c(57:60, 62:65), c(1,2,4,8,10)]
rownames(mental_indices_coefs_) = NULL
mental_indices_coefs_$Policies = c('Social Care', 
                                   'Housing & Transport',
                                   'Environment & Culture',
                                   'Education',
                                   'Social Care', 
                                   'Housing & Transport',
                                   'Environment & Culture',
                                   'Education')
mental_indices_coefs_[,1] = NULL
mental_indices_coefs_ %<>% dplyr::select(Policies, everything())
colnames(mental_indices_coefs_)[1] = ' '
fun = function(x) {
  x = ifelse(x<0, paste0('-', as.character(substr(as.character(x), 3, nchar(x)))), 
                         ifelse(x>0, as.character(substr(as.character(x), 2, nchar(x))),
                                as.character('.00')))
  x = ifelse(nchar(x)<3, paste0(x, '.00'), x)
  return(x)
}

#colnames(mental_indices_coefs_initial) = ''
fin_mental_indices = dplyr::bind_cols(mental_indices_coefs_, mental_indices_coefs_initial) %>% 
   dplyr::select(all_of(c(matrix(names(.), ncol = 5, byrow = TRUE))))

fin_mental_indices = as.data.frame(fin_mental_indices[,-2])

# merge cells
fin_mental_indices$a = paste(fin_mental_indices[,2], fin_mental_indices[,3])
fin_mental_indices$b = paste(fin_mental_indices[,4], fin_mental_indices[,5])
fin_mental_indices$c = paste(fin_mental_indices[,6], fin_mental_indices[,7])
fin_mental_indices$d = paste(fin_mental_indices[,8], fin_mental_indices[,9])
fin_mental_indices = fin_mental_indices[,c(1,10,11,12,13)]

colnames(fin_mental_indices) = c('',  
               "Mental Index", 
               "1.Incapacity Benefits",
               '2.Antidepressants',
               '3.Hospital Admissions')

# palette
pal.fnc = colorRamp(c("firebrick1", "white", "springgreen"))
mental_indices_coefs_ = repair_names(mental_indices_coefs_)
test = as_tibble(mental_indices_coefs_)
max.val = max(test[ , sapply(test, is.numeric)], na.rm=TRUE)

fin_mental_indices[,-1] %<>%
  mutate_if(is.character, function(x) {
    text_spec(fun(x), 'html', bold = T, color=grey(.3),
              background = rgb(pal.fnc(normalize(as.numeric(gsub(' \\**|\\^', '', x))/max.val)),
                               maxColorValue=255),
              align = 'center', monospace =F
              )
  }) 

# print
 fin_mental_indices %>%
  kbl(#caption = "Estimated Policy Effects on Mental Health by Sub-Indices",
      booktabs = F, escape = F, centering = T) %>%
  kable_styling(font_size = 15, bootstrap_options = 'responsive',
                html_font = 'arial', full_width = F)%>%
  pack_rows("Long-Run", 1, 4) %>%
  pack_rows("Short-Run", 5, 8) %>%
  row_spec(0, align='left') %>%
  column_spec(1, width = '6cm') 
```



#
#
#
#



\newpage



```{r, fig.height=5, fig.width=8}
par(mfrow=c(1,2))
par(mar = c(5, 1, 3, 0))
plot_list1 = plot_effects(rhs_selected = c("e_HE1",
                                           "e_sc1",
                                           'e_ho1',
                                           'e_nh1',
                                           'e_ed1'))
plot_list2 = plot_effects()
plot(plot_list1[[1]])
title('T                SHORT RUN             T + 1',
      cex.main = 1.6,  font.main = 2,
      col.main = 'darkred', outer = F)
plot(plot_list2[[1]])
title('T                LONG RUN               T + 2',
      cex.main = 1.6, font.main = 2,
      col.main = 'darkgreen', outer = F)
```


```{r fig.height=3, fig.width=4}
df_lad$year = as.factor(df_lad$year)
panel =  panel_data(df_lad, id = LAD21CD, wave = year)

panel$year = as.numeric(as.character(panel$year))

#par(mfrow=c(2,2))
l0 = panel  %>% 
  filter(!LAD21CD %in% outliers) %>% 
  ggplot(aes(year, samhi_index)) +
  scale_x_continuous(name = NULL, 
                    breaks = 2011:2019)+ 
  scale_y_continuous(name = NULL, 
                    breaks = seq(-3, 1.5, 1)) + 
  theme(axis.text = element_text(size = 12)) + 
  theme(axis.title.x = element_text(size = 14)) +
  geom_line(aes(group = LAD21CD), color = "lightblue") +
         geom_smooth(method = loess, se = F, fullrange = T, color="darkred") +
  theme_pubclean()

l1 = panel  %>% 
  filter(!LAD21CD %in% outliers) %>% 
  ggplot(aes(year, education)) +
  scale_x_continuous(name = NULL, 
                    breaks = 2011:2019)+ 
  scale_y_continuous(name = NULL, 
                    breaks = seq(0.2, 1.2, 0.2)) + 
  theme(axis.text = element_text(size = 12)) + 
  theme(axis.title.x = element_text(size = 14)) +
  geom_line(aes(group = LAD21CD), color = "lightblue") +
         geom_smooth(method = loess, se = F, fullrange = T, color="darkred") +
  theme_pubclean()

l2 = panel  %>% 
  filter(!LAD21CD %in% outliers) %>% 
  ggplot(aes(year, pub_health_soc_care)) +
  scale_x_continuous(name = NULL, 
                    breaks = 2011:2019)+ 
  scale_y_continuous(name = NULL, 
                    breaks = seq(0.2,0.9, 0.2)) + 
  theme(axis.text = element_text(size = 12)) + 
  theme(axis.title.x = element_text(size = 14)) +
  geom_line(aes(group = LAD21CD), color = "lightblue") +
         geom_smooth(method = loess, se = F, fullrange = T, color="darkred") +
  theme_pubclean()


outliers = panel %>% 
  filter((housing_transport > .15 & year == 2011)) %>%
  pull(LAD21CD)

l3 = panel  %>% 
  filter(!LAD21CD %in% outliers) %>% 
  ggplot(aes(year, housing_transport)) +
  scale_x_continuous(name = NULL, 
                    breaks = 2011:2019)+ 
  scale_y_continuous(name = NULL, 
                    breaks = seq(0,0.2, 0.05)) + 
  theme(axis.text = element_text(size = 12)) + 
  theme(axis.title.x = element_text(size = 14)) +
  geom_line(aes(group = LAD21CD), color = "lightblue") +
         geom_smooth(method = loess, se = F, fullrange = T, color="darkred") +
  theme_pubclean()

outliers = panel %>% 
  filter((environment_planning_cultural > .3 & year == 2011)) %>%
  pull(LAD21CD)

l4 = panel  %>% 
  filter(!LAD21CD %in% outliers) %>% 
  ggplot(aes(year, environment_planning_cultural)) +
  scale_x_continuous(name = NULL, 
                    breaks = 2011:2019)+ 
  scale_y_continuous(name = NULL, 
                    breaks = seq(0,0.4, 0.1)) + 
  theme(axis.text = element_text(size = 12)) + 
  theme(axis.title.x = element_text(size = 14)) +
  geom_line(aes(group = LAD21CD), color = "lightblue") +
         geom_smooth(method = loess, se = F, fullrange = T, color="darkred") +
  theme_pubclean()
```

```{r fig.height=8, fig.width=10}
library(ggpubr)
ggarrange(list_plots[[5]],
          list_plots[[4]],
          list_plots[[3]],
          list_plots[[2]],
          list_plots[[1]],
          labels = c('Incapacity Benefits Rate',
                     'Depression Rate',
                     'Antidepressants Rate',
                     'Hospital Attendances Score',
                     'Mental Health Index'
),
          ncol = 3, nrow = 2,
font.label = list(size = 14), align ='h')
ggsave("C:/Users/ru21406/YandexDisk/PhD Research/health-ses-policies/output/mhealth_lineplots.jpeg")
```


```{r fig.height=8, fig.width=10}
library(ggpubr)
ggarrange(list_plots[[6]],
          list_plots[[7]],
          list_plots[[8]],
          list_plots[[9]],
          list_plots[[10]],
          list_plots[[11]],
          labels = c('Public Health & Social Care',
                    'Healthcare',
                    'Education',
                    'Environment',
                    'Law and Order',
                    'Infrastructure'
),
          ncol = 3, nrow = 2,
font.label = list(size = 14))
ggsave("C:/Users/ru21406/YandexDisk/PhD Research/health-ses-policies/output/spending_lineplots.jpeg")
```

```{r fig.height=3, fig.width=5}
ggarrange(l0,
          labels = 'Mental Health Index',
          ncol = 1, nrow = 1)
```



```{r}
panel2 =  panel_data(df, id = lsoa11, wave = year)
filtered_id = df %>% filter(year == 2011) %>% slice_sample(n=1000) %>% pull(lsoa11)
df  %>% 
 filter(lsoa11 %in% filtered_id) %>%
  ggplot(aes(year, environment_planning_cultural)) +
  scale_x_continuous(name = NULL, 
                    breaks = 2011:2019)+ 
  scale_y_continuous(name = NULL, 
                    breaks = seq(0,0.4, 0.1)) + 
  theme(axis.text = element_text(size = 12)) + 
  theme(axis.title.x = element_text(size = 14)) +
  geom_line(aes(group = lsoa11), color = "lightblue") +
         geom_smooth(method = loess, se = F, fullrange = T, color="darkred") +
  theme_pubclean()
```


